name: Synk APKtool

on:
  workflow_dispatch:
  schedule: 
  - cron: "0 0 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync and merge the upstream repository with your forked repository
        uses: dchourasia/sync-upstream-repo@1.01
        with:
          upstream_repo: "https://github.com/iBotPeaches/Apktool.git"
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GITHUB_TOKEN }}
